version: '3.7'

services:
  pgadmin:
    restart: always
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      GUNICORN_THREADS: 4
      PGADMIN_LISTEN_PORT: 19000
    volumes:
      - ./pgadmin/pgadmin4-servers.json:/pgadmin4/servers.json
    depends_on:
      - postgresql
    ports:
      - "19000:19000"
    labels:
      - "toy-db"
